Views
gracekabaghe/rails-simple-site pull request #5
Opened 2022-03-01 18:19 UTC by gracekabaghe

- Use preprocessed HTML file with embedded Ruby code.
- Use layouts and templates for shared content.

2022-03-01 20:06 UTC, andersonlebon requested changes
## Hi @gracekabaghe 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 20:06 UTC, andersonlebon commented on db/migrate/20220228181206_add_comments_ref_to_posts.rb
>  end
- [x] Unnecessary migration to reference the post in the comment table because you have already referenced it when you create the comments table. Kindly remove this migration. It s giving error :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156232811-71557293-a890-4b4a-93d1-c2f8139a5905.png)

2022-03-01 20:06 UTC, andersonlebon commented on db/migrate/20220228183400_add_posts_ref_to_comments.rb
>  end
- [x] Unnecessary migration to reference the post in the comment table because you have already referenced it when you create the comments table. Kindly remove this migration. It s giving error :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156232811-71557293-a890-4b4a-93d1-c2f8139a5905.png)

- [x]  To remove all errors in your migrations kindly go to [this migration](https://github.com/gracekabaghe/rails-simple-site/blob/ff0fecbe82eb1f4af69d14bb4fb6059fa7a20796/db/migrate/20220228163529_add_posts_ref_to_likes.rb#L3) and change `user` to `post` because you are referencing the post in the Like table. this will be the final migration. :point_down: 

```rb  
class AddPostsRefToLikes < ActiveRecord::Migration[7.0]
  def change
    add_reference :likes, :post, null: false, foreign_key: true
  end
end
```

2022-03-01 20:06 UTC, andersonlebon commented on app/controllers/posts_controller.rb
>  end
- [x] I am getting this error when accessing a single post :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156238109-9c7235c2-dcd9-4e4a-9db7-e65717569f79.png)

- [x] You can solve this by getting the user an his posts like this :point_down: 

```rb 
def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
  end

```

2022-03-01 20:06 UTC, andersonlebon commented on app/views/posts/show.html.erb
> +            <div class='post-com-lik-counters'>
- [ ] Kindly not `<%= @post.user.name %>` this relationship does not exist in your table, if you want to get the user name kindly refer to the `<%= @user.name %>` which is defined in the post#show controller. I am getting this error :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156240033-d5af431a-9dac-4d15-aa85-009289dba199.png)

2022-03-01 20:06 UTC, andersonlebon commented on app/views/posts/show.html.erb
> +    </div>
- [ ] Kindly note that `<%= comment.user.name%>` this relationship does not exist in your comment table, if you want to get the user name kindly refer to the `<%= @user.name %>` which is defined in the post#show controller. I am getting this error :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156240358-822541b7-132d-40e0-b2bf-c2a718658aec.png)

2022-03-01 20:06 UTC, andersonlebon commented on app/views/posts/index.html.erb
> +        <% end %>
- [ ] Kindly note that `<%= comment.user.name%>` this relationship does not exist in your comment table, if you want to get the user name kindly refer to the `<%= @user.name %>` which is defined in the post#show controller. I am getting this error :point_down: 

![image](https://user-images.githubusercontent.com/65068771/156240628-e1953fb0-fdd1-43dc-a555-8c81d556846e.png)

2022-03-02 10:23 UTC, hiromataba approved these changes
# Status: Approved :tada:  :champagne:  :confetti_ball: 
Hi  :wave:   :wave: @gracekabaghe , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Your README file looks very professional :+1: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please add `seeds` to your projects to help reviewers or anyone who clones your projects to get some data from the seed file

- [ ] [OPTIONAL] Please fix the typo , you added an extrat space after the `:`

![image](https://user-images.githubusercontent.com/75126481/156343319-caa04779-00eb-4394-aded-29516470f94a.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 10:32 UTC, merged